services:
  - type: web
    name: sd-traffic-transportation-api
    runtime: python
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
